run:
  timeout: 5m
  tests: true
  build-tags:
    - netgo

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true
  
  gocyclo:
    min-complexity: 15
  
  gofmt:
    simplify: true
  
  goimports:
    local-prefixes: ai-teams
  
  gosec:
    severity: medium
    confidence: medium
  
  govet:
    check-shadowing: true
    enable-all: true
    disable:
      - fieldalignment
  
  ineffassign:
    check-generated: false
  
  misspell:
    locale: US
  
  nakedret:
    max-func-lines: 30
  
  unparam:
    check-exported: false
  
  unused:
    check-exported: false
  
  whitespace:
    multi-if: false
    multi-func: false

linters:
  enable:
    - bodyclose
    - deadcode
    - depguard
    - dogsled
    - dupl
    - errcheck
    - exhaustive
    - exportloopref
    - gochecknoinits
    - gochecknoglobals
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - godot
    - godox
    - goerr113
    - gofmt
    - gofumpt
    - goheader
    - goimports
    - gomnd
    - gomodguard
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - ineffassign
    - lll
    - makezero
    - misspell
    - nakedret
    - nestif
    - noctx
    - nolintlint
    - rowserrcheck
    - sqlclosecheck
    - staticcheck
    - structcheck
    - stylecheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - varcheck
    - wastedassign
    - whitespace
  
  disable:
    - exhaustivestruct
    - forbidigo
    - funlen
    - gci
    - gochecknoinits
    - gochecknoglobals
    - godot
    - goerr113
    - goheader
    - gomnd
    - gomodguard
    - nlreturn
    - paralleltest
    - prealloc
    - testpackage
    - thelper
    - wrapcheck
    - wsl

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gocyclo
        - errcheck
        - dupl
        - gosec
        - goconst
    
    - path: benchmark_test\.go
      linters:
        - gocyclo
        - errcheck
        - dupl
    
    - text: "G204: Subprocess launched with variable"
      linters:
        - gosec
    
    - text: "G104: Errors unhandled"
      linters:
        - gosec
    
    - text: "Use of weak random number generator"
      linters:
        - gosec
  
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
  new: false

output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true
  uniq-by-line: true
  sort-results: true